import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_email(news_items):
    """
    Send formatted HTML email with news summaries and RAG context
    
    Args:
        news_items (list): List of summarized news items with RAG metadata
    """
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "📰 AI Daily News Digest (with RAG Context)"
    msg["From"] = sender
    msg["To"] = receiver

    # HTML START
    html = """
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; color: #333; }
            .header { text-align: center; color: #2c3e50; margin-bottom: 20px; }
            .news-card { 
                margin-bottom: 25px; 
                padding: 15px; 
                border-radius: 10px; 
                border-left: 5px solid #1a73e8;
                background-color: #f9f9f9;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .title { color: #1a73e8; font-size: 18px; font-weight: bold; margin: 0 0 10px 0; }
            .meta { font-size: 12px; color: #666; margin: 5px 0; }
            .summary { line-height: 1.6; color: #333; margin: 10px 0; }
            .read-more-btn { 
                display: inline-block; 
                background-color: #1a73e8; 
                color: white; 
                padding: 10px 20px; 
                text-decoration: none; 
                border-radius: 5px; 
                font-weight: bold; 
                margin-top: 10px;
                font-size: 14px;
            }
            .read-more-btn:hover { 
                background-color: #1557b0; 
            }
            .rag-context { 
                background-color: #e8f4f8; 
                padding: 10px; 
                border-radius: 5px; 
                margin-top: 10px; 
                font-size: 12px;
            }
            .rag-title { color: #0066cc; font-weight: bold; margin-bottom: 5px; }
            .related-item { margin: 5px 0; padding-left: 10px; border-left: 2px solid #0066cc; }
            .similarity { color: #0066cc; font-size: 11px; }
            .footer { text-align: center; margin-top: 30px; color: #999; font-size: 12px; }
            hr { border: none; border-top: 1px solid #ddd; }
        </style>
    </head>
    <body>
        <div class="header">
            <h2>📰 AI Daily News Digest</h2>
            <p><em>Powered by RAG (Retrieval-Augmented Generation)</em></p>
        </div>
        <hr>
    """

    # NEWS CARDS WITH RAG CONTEXT
    for i, item in enumerate(news_items, start=1):
        html += f"""
        <div class="news-card">
            <div class="title">📰 News {i}: {item['title']}</div>
            
            <div class="meta">
                <b>Source:</b> {item['source']}
            </div>

            <div class="summary">
                <b>Summary:</b><br>
                {item['summary']}
            </div>
        """
        
        # Add read more button with URL
        if item.get('url'):
            html += f"""
            <a href="{item['url']}" class="read-more-btn">🔗 Read Full Article</a>
            """
        
        # Add RAG context if available
        if item.get('rag_used') and item.get('related_articles'):
            html += f"""
            <div class="rag-context">
                <div class="rag-title">🔍 Context (Similar Articles Found)</div>
            """
            
            for related in item.get('related_articles', [])[:2]:  # Show top 2 related
                html += f"""
                <div class="related-item">
                    <b>{related['title'][:60]}...</b><br>
                    Source: {related['source']} 
                    <span class="similarity">({int(related['similarity_score']*100)}% match)</span><br>
                    {related['summary'][:120]}...
                </div>
                """
            
            html += """
            </div>
            """
        
        html += """
        </div>
        """

    html += """
        <hr>
        <div class="footer">
            <p>Generated by AI News System with RAG</p>
            <p><small>Each article is summarized using context from similar recent articles</small></p>
        </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(html, "html"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, receiver, msg.as_string())
        server.quit()
        print(" Email sent successfully!")
        
    except smtplib.SMTPAuthenticationError:
        print(" Email failed: Invalid sender/password. Check .env file")
    except smtplib.SMTPException as e:
        print(f" Email failed: {e}")
    except Exception as e:
        print(f" Unexpected error: {e}")